# Generated by Django 4.0.5 on 2022-06-09 05:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('slides', wagtail.blocks.StructBlock([('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False)), ('button_text', wagtail.blocks.TextBlock(max_length=255, required=False)), ('button_page', wagtail.blocks.PageChooserBlock(required=False))])))]))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
